image: ubuntu/18.04
packages:
  - mlton
  - polyml
  - ninja-build
  - wget
secrets:
  - 1011a889-f276-420d-ba69-b2dc27f6c5cc
sources:
  - hg+ssh://hg@hg.sr.ht/~cannam/bisquay
tasks:
  - setup: |
      ssh-keyscan -H hg.sr.ht >> .ssh/known_hosts
      echo '{"accounts": {"sourcehut": "cannam"}}' > .repoint.json
      wget https://github.com/mesonbuild/meson/releases/download/0.56.0/meson-0.56.0.tar.gz
      tar xvf meson-0.56.0.tar.gz
      sudo ln -s $(pwd)/meson-0.56.0/meson.py /usr/bin/meson
      cd bisquay
      ./repoint install
      cat meson_options.txt.in | sed "s/value: 'polyml'/value: 'mlton_noffi'/" > meson_options.txt
      meson build --buildtype release
  - build: |
      cd bisquay
      ninja -C build
  - test: |
      cd bisquay
      ./build/bsq_test
triggers:
  - action: email
    condition: always
    to: chris.cannam@breakfastquay.com
