image: ubuntu/lts
packages:
  - mlton
  - polyml
  - ninja-build
  - wget
secrets:
  - 1011a889-f276-420d-ba69-b2dc27f6c5cc
sources:
  - hg+ssh://hg@hg.sr.ht/~cannam/bisquay
tasks:
  - setup: |
      ssh-keyscan -H hg.sr.ht >> .ssh/known_hosts
      echo '{"accounts": {"sourcehut": "cannam"}}' > .repoint.json
      wget https://github.com/mesonbuild/meson/releases/download/0.56.0/meson-0.56.0.tar.gz
      tar xvf meson-0.56.0.tar.gz
      sudo ln -s $(pwd)/meson-0.56.0/meson.py /usr/bin/meson
  - build: |
      cd bisquay
      ./repoint install
      meson build_poly -Dsml_buildtype=polyml
      meson build_mlton_noffi -Dsml_buildtype=mlton_noffi
      ninja -C build_poly
      ninja -C build_mlton_noffi
  - test: |
      cd bisquay
      ./build_poly/bsq_test
      ./build_mlton_noffi/bsq_test
triggers:
  - action: email
    condition: always
    to: chris.cannam@breakfastquay.com
