image: archlinux
packages:
  - mlton
  - polyml
  - ninja
  - meson
  - wget
secrets:
  - 1011a889-f276-420d-ba69-b2dc27f6c5cc
sources:
  - hg+ssh://hg@hg.sr.ht/~cannam/bisquay
tasks:
  - setup: |
      ssh-keyscan -H hg.sr.ht >> .ssh/known_hosts
      echo '{"accounts": {"sourcehut": "cannam"}}' > .repoint.json
  - build: |
      cd bisquay
      ./repoint install
      meson build_poly -Dsml_buildtype=polyml
      meson build_mlton_noffi -Dsml_buildtype=mlton_noffi
      ninja -C build_poly
      ninja -C build_mlton_noffi
      # Test whether a build using default-int32 MLton also works:
      mlton test-sml.mlb
      # And build the documentation:
      meson compile -C build_mlton_noffi doc
  - test: |
      cd bisquay
      ./build_poly/bsq_test
      ./build_mlton_noffi/bsq_test
      ./test-sml
triggers:
  - action: email
    condition: always
    to: chris.cannam@breakfastquay.com
